"""expiry indexes for cleanup

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 02:30:02.731146
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_codes_expires_at"), ["expires_at"], unique=False)

    with op.batch_alter_table("pending_logins", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pending_logins_expires_at"), ["expires_at"], unique=False)

    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tokens_expires_at"), ["expires_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tokens_expires_at"))

    with op.batch_alter_table("pending_logins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pending_logins_expires_at"))

    with op.batch_alter_table("auth_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_codes_expires_at"))

    # ### end Alembic commands ###
