"""link grant to auth code

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 11:56:32.367605
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("auth_code_hash", sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f("ix_grants_auth_code_hash"), ["auth_code_hash"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grants_auth_code_hash"))
        batch_op.drop_column("auth_code_hash")

    # ### end Alembic commands ###
