"""resource grants and user credentials

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 12:37:58.734013
"""

import time
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_grants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=340), nullable=False),
        sa.Column("connector", sa.String(length=32), nullable=False),
        sa.Column("resource", sa.String(length=255), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject", "connector", "resource", name="uq_resource_grant"),
    )
    with op.batch_alter_table("resource_grants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_resource_grants_subject"), ["subject"], unique=False)

    op.create_table(
        "user_credentials",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("access_token_enc", sa.Text(), nullable=False),
        sa.Column("refresh_token_enc", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.Column("scopes", sa.String(length=512), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "provider"),
    )
    # ### end Alembic commands ###

    # Права, повторяющие поведение 0.2: роли readonly и member видят все ресурсы всех коннекторов.
    # Чтобы ограничить доступ — удалите их (rugw grants remove) и выдайте узкие.
    grants = sa.table(
        "resource_grants",
        sa.column("subject", sa.String),
        sa.column("connector", sa.String),
        sa.column("resource", sa.String),
        sa.column("level", sa.String),
        sa.column("created_at", sa.Float),
    )
    now = time.time()
    op.bulk_insert(
        grants,
        [
            {"subject": "role:readonly", "connector": "*", "resource": "*", "level": "read", "created_at": now},
            {"subject": "role:member", "connector": "*", "resource": "*", "level": "write", "created_at": now},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_credentials")
    with op.batch_alter_table("resource_grants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_grants_subject"))

    op.drop_table("resource_grants")
    # ### end Alembic commands ###
