"""credentials generation for CAS

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 13:10:41.829840
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_credentials", schema=None) as batch_op:
        batch_op.add_column(sa.Column("generation", sa.Integer(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_credentials", schema=None) as batch_op:
        batch_op.drop_column("generation")

    # ### end Alembic commands ###
