"""audit request id

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-06 13:51:22.271587
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("request_id", sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f("ix_audit_events_request_id"), ["request_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_request_id"))
        batch_op.drop_column("request_id")

    # ### end Alembic commands ###
