"""groups and service credentials

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-08 08:00:19.838541
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_members",
        sa.Column("group", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("group", "email"),
    )
    with op.batch_alter_table("group_members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_group_members_email"), ["email"], unique=False)

    op.create_table(
        "service_credentials",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("secret_enc", sa.Text(), nullable=False),
        sa.Column("generation", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("provider"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_credentials")
    with op.batch_alter_table("group_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_members_email"))

    op.drop_table("group_members")
    # ### end Alembic commands ###
